<?php
/**
* @file
* Once the user is login set them into groups.
*/

/*
 * Implement hook_login() 
 */
function password_changer_setgroup_user_login(&$edit, $account) {
     
  //Get Roles in the system and flip and make the role name the key
  $roles = array_flip(user_roles());  

  if (preg_match('/^[0-9a-zA-z]{2}[0-9]{7}/',$account->name)) {
     if (array_key_exists('UNIVERSAL STUDENTS', $roles)) {
      //Add give Employee or Staff the Employee role
        if (!in_array('UNIVERSAL STUDENTS', $account->roles)) {
          $user_role = $roles['UNIVERSAL STUDENTS'];
        }  
     }
  }
  else {
    if (array_key_exists('Employees', $roles)) {
     //Add give student the Employee role
      if (!in_array('Employees', $account->roles)) { 
         $user_role = $roles['Employees'];
      }   
    }
  }
  
 
   //If $user_role is set then save the user 
   if (isset($user_role)) {
     //Update user record
     user_multiple_role_edit(array( $account->uid), 'add_role', $user_role);
   }
 }